"""Build the local research portfolio and its downloadable asset catalogue."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/"docs/portfolio"
NAV='''<a href="index.html#study">Study</a><a href="index.html#simulation">Simulation</a><a href="index.html#downloads">Downloads</a><a href="hardware.html">Hardware</a><a href="reproduce.html">Reproduce</a>'''
def page(title,body):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="William's MSc Robotics research: typed language, structured plans and verified warehouse navigation. Explore the evidence, simulation and engineering artifacts."><title>{title} · NL → Nav2</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"></head><body><a class="skip" href="#main">Skip to content</a><header class="topbar"><div class="wrap"><a class="brand" href="index.html">NL → NAV2 <span>/ research portfolio</span></a><nav aria-label="Main navigation">{NAV}</nav></div></header><main id="main">{body}</main><footer><div class="wrap"><span>William · MSc Robotics · Middlesex University Dubai<br>PDE4445 · Simulation study · Updated 12 September 2026</span><span><a href="https://github.com/Twillur/PDE4445-LLM-Nav2-Planner">Source repository</a> · <a href="https://twillur.github.io/PDE4445-Robotics-Dissertation/">Project journal</a><br><a href="MEDIA.md">Media provenance</a> · <a href="../validation/README.md">Validation records</a></span></div></footer><script src="assets/route-data.js"></script><script src="app.js"></script></body></html>'''

figures=[
    ("semantic-map","Maps","Named warehouse map","20 location names over the actual world geometry."),
    ("recorded-routes","Maps","Recorded robot routes","Three odometry traces; selected 1-, 3- and 5-goal replays."),
    ("reliability","Results","Reliability by category","Strict success with scoring units shown explicitly."),
    ("prompt-comparison","Results","Prompt v1 versus v2","Automatic L1–L3 success over three trials."),
    ("latency","Results","Translation latency","Recorded v2 planner-call times, n=300."),
    ("architecture","System","Current runtime architecture","Typed input, shared execution gate, executor and Nav2."),
    ("fallback","System","Conditional fallback behaviour","The representation gap and later runtime checks."),
    ("hardware-architecture","System","Proposed physical system","An unbuilt hardware concept; separate from the study."),
]
cards="".join(f'''<article class="card" data-category="{category}"><a href="assets/{slug}.png"><img loading="lazy" src="assets/{slug}.svg" alt="{title}"></a><h3>{title}</h3><p>{description}</p><div class="formats"><a href="assets/{slug}.png" download>PNG ↓</a><a href="assets/{slug}.svg" download>SVG ↓</a><a href="assets/{slug}.pdf" download>PDF ↓</a></div></article>''' for slug,category,title,description in figures)
levels=[("L1","Direct","Go to the loading dock."),("L2","Spatial","Move along the east wall from south to north."),("L3","Multi-step","Patrol aisles 1 and 3, then return to the charging dock."),("L4","Conditional","Inspect A; if it is unreachable, inspect B instead."),("L5","Ambiguous","Go check that thing near the door.")]
level_cards="".join(f'<article class="level"><b>{level}</b><h3>{title}</h3><p>“{example}”</p></article>' for level,title,example in levels)
index=f'''
<div class="wrap"><section class="hero"><div><span class="tag">MSc Robotics · Research in simulation</span><h1>From instructions<br>to robot motion.</h1><p>A typed command becomes a structured plan, then a warehouse robot follows it. The research asks how reliably that translation holds as the instructions change.</p><div class="actions"><a class="button" href="#simulation">Watch the robot ↗</a></div><p class="small">Natural Language Task Planning for Autonomous Ground Robot Navigation via Large Language Models</p></div><figure class="visual"><img src="media/warehouse-overview.png" alt="Actual Gazebo warehouse with four shelf rows and a TurtleBot3 at its starting dock"><figcaption class="caption">01 / Actual Gazebo warehouse · TurtleBot3 Waffle · 12 September capture</figcaption></figure></section>
<div class="metrics"><div class="metric"><strong>100</strong><span>authored commands<br>five categories, 20 each</span></div><div class="metric"><strong>20</strong><span>named map locations<br>coordinates resolved by the executor</span></div><div class="metric"><strong>2.23 s</strong><span>mean translation latency<br>v2, 300 recorded calls</span></div><div class="metric"><strong>9 / 9</strong><span>goals in three selected replays<br>odometry cross-checked; pre-fix runtime</span></div></div>

<section class="section" id="study"><div class="section-heading"><div><span class="eyebrow">01 / The study</span><h2>Language is only half<br>of the interface.</h2></div><p>A command can be clear while the plan format cannot express its condition. The evidence identifies representation as one limiting factor in reliable translation.</p></div><div class="grid5">{level_cards}</div><p class="small">Illustrative category descriptions. The authored L1–L5 scale is not a validated universal measure of language difficulty.</p><figure class="plate"><img loading="lazy" src="assets/reliability.svg" alt="L1 96.7 percent, L2 95 percent, L3 95 percent over 60 records each; L4 55 percent and L5 85 percent over 20 items each"></figure><div class="note"><strong>The distinction matters.</strong> L5 can pass by asking for clarification. L4 conditional commands often require behaviour the original format cannot express. The L4/L5 gap alone is not statistically significant at 0.05 (two-sided Fisher p≈0.082); the argument rests on inspected failures and the targeted v3 experiment. <a href="EVIDENCE.md">Read the evidence and limitations →</a></div></section>

<section class="section" id="system"><div class="section-heading"><div><span class="eyebrow">02 / The system</span><h2>One call. Explicit steps.</h2></div><p>No voice input, agent loop or re-prompting. The model names places; the executor resolves those names and sends navigation goals to Nav2.</p></div><figure class="plate"><img loading="lazy" src="assets/architecture.svg" alt="Current runtime from typed input through one LLM call, JSON plan, execution validation and Nav2"></figure><div class="grid2" style="margin-top:24px"><article class="plate"><h3>A map is the coordinate authority.</h3><p class="small">The model outputs names such as <code>loading_dock</code>. Unknown primary or fallback names are rejected by the current execution gate. A valid name can still be the wrong destination for the command.</p><a href="assets/semantic-map.pdf">Inspect the map →</a></article><article class="plate"><h3>A condition needs a branch.</h3><p class="small">v3 adds <code>goto_fallback</code> and <code>fallback_target</code>, with accompanying prompt instructions. Schema adherence rises from 55/60 to 60/60 on L4; the selected three-command branch diagnostic rises from 0/9 to 7/9.</p><a href="assets/fallback.pdf">Inspect the failure mechanism →</a></article></div></section>

<section class="section" id="simulation"><div class="section-heading"><div><span class="eyebrow">03 / Simulation evidence</span><h2>See the robot.<br>Then inspect its route.</h2></div><p>Genuine Gazebo captures and recorded odometry. Visual evidence is linked to its run, rather than presented as a general reliability claim.</p></div><div class="grid2"><article class="media-card"><video controls playsinline preload="metadata" poster="media/warehouse-overview.png" aria-label="Time-compressed Gazebo navigation to the loading dock"><source src="media/warehouse-navigation.mp4" type="video/mp4"><track kind="captions" src="media/warehouse-navigation.vtt" srclang="en" label="English" default></video><div class="body"><h3>Loading-dock navigation</h3><p>A fresh capture using the corrected runtime. Nav2 reported 1/1 goals reached. The clip compresses 130 captured frames into 8.67 seconds; it is not real-time playback.</p><a href="media/warehouse-navigation.mp4" download>Download MP4 ↓</a> · <a href="../validation/portfolio-capture-20260912T094720Z/executor.log">Goal log</a></div></article><article class="media-card"><img loading="lazy" src="media/robot-detail.png" alt="Close view of the actual TurtleBot3 Waffle model and its laser scan in Gazebo"><div class="body"><h3>The simulated robot and its sensor</h3><p>TurtleBot3 Waffle in the actual warehouse. Blue rays show the simulated laser scan. This is a static capture, not a photograph of purchased hardware.</p><a href="media/robot-detail.png" download>Download full screenshot ↓</a></div></article></div>
<div class="plate replay" style="margin-top:28px"><div><svg id="route-map" viewBox="0 0 520 520" role="img" aria-label="Interactive replay of recorded warehouse robot positions"></svg></div><div><span class="eyebrow">Recorded odometry / interactive replay</span><h3 style="margin-top:15px">Follow the measured positions.</h3><p class="small">These three archived replays used the pre-fix executor. The display reconstructs stored positions; it does not run a simulator or a new planner call.</p><label for="route-select">Choose a recorded route</label><select id="route-select"><option value="0">L1 · Direct destination</option><option value="1">L2 · East-wall traversal</option><option value="2" selected>L3 · Aisles 1 and 3 patrol</option></select><ol id="route-targets"></ol><label for="route-progress">Replay position</label><input id="route-progress" type="range" min="0" max="1000" value="0"><div id="route-time" class="replay-meta" aria-live="off"></div><button class="primary" id="play-route" aria-pressed="false">Play replay</button><p class="small">Playback: 8× recorded simulation time. Numbered dots mark requested destinations.</p><a href="assets/recorded-routes.pdf">Download all three route plots ↓</a></div></div></section>

<section class="section" id="validation"><div class="section-heading"><div><span class="eyebrow">04 / Engineering status</span><h2>What is verified.<br>What remains open.</h2></div><p>The evidence comes from different stages. New execution checks do not change the original translation scores.</p></div><div class="grid2"><div class="plate"><div class="status-row"><strong>August language evaluation<br><span class="pill">Archived</span></strong><p>v1/v2: 300 records each. v3: 60 L4 records. Original results and grading files preserved.</p></div><div class="status-row"><strong>Selected Gazebo replays<br><span class="pill">Verified</span></strong><p>1/1 + 3/3 + 5/5 goals, with recorded positions within 0.25 m. Single runs; no obstacle trials.</p></div><div class="status-row"><strong>Runtime corrections<br><span class="pill">62 tests passed</span></strong><p>Shared input gate, conditional fallback and failure status. Tests passed in Windows and WSL; package rebuilt.</p></div><div class="status-row"><strong>v3 semantics + physical trials<br><span class="pill pending">Outstanding</span></strong><p>Human semantic grading, independent grading and controlled Gazebo fallback trials remain necessary. No hardware deployment.</p></div></div><div class="dark-block"><span class="eyebrow">A useful engineering lesson</span><h3 style="font-size:1.8rem;margin-top:20px">Valid JSON is not<br>a correct robot task.</h3><p>The saved v2 alternative-destination example still visits B unconditionally. A runtime gate can reject an invented name; it cannot infer that an otherwise valid step is wrong for the operator's intent.</p><a href="../validation/runtime-fixes-20260912/README.md">Read the runtime correction record →</a><p class="small">Also documented: prompt/test overlap, uncertain grading blinding, mixed denominators, one grader and one model/map.</p></div></div></section>

<section class="section" id="hardware"><div class="section-heading"><div><span class="eyebrow">05 / Beyond simulation</span><h2>A physical build,<br>costed as a proposal.</h2></div><p>Candidate components, supplier snapshots, USD/AED planning costs and integration decisions. These are future options, not equipment used to obtain the study results.</p></div><figure class="plate"><img loading="lazy" src="assets/hardware-architecture.svg" alt="Proposed physical robot with onboard compute, LiDAR, motor controller and protected power"></figure><div class="actions"><a class="button" href="hardware.html">Explore hardware &amp; costs →</a><a class="button secondary" href="reproduce.html#stack">Software &amp; plugins →</a></div></section>

<section class="section downloads" id="downloads"><div class="section-heading"><div><span class="eyebrow">06 / Presentation library</span><h2>Take the evidence<br>into your slides.</h2></div><p>PNG for slides, SVG for editing and PDF for print. Captions retain the sample sizes, dates and limits behind each figure.</p></div><div class="filters" role="group" aria-label="Filter downloadable figures"><button aria-pressed="true" data-filter="All">All figures</button><button aria-pressed="false" data-filter="Maps">Maps</button><button aria-pressed="false" data-filter="Results">Results</button><button aria-pressed="false" data-filter="System">System</button></div><p id="filter-count" class="small" aria-live="polite">8 figures</p><div class="grid3">{cards}</div><div class="grid2" style="margin-top:28px"><article class="plate report-card"><img loading="lazy" src="media/report-preview.png" alt="First page of the eight-page IEEE-format report draft"><div><h3>Eight-page report draft</h3><p class="small">Includes the original evaluation and three Gazebo replays. It predates the later runtime corrections; read the accompanying update notes before reuse.</p><p class="small">Under assessment; published after the module result.</p></div></article><article class="plate"><h3>Reusable media</h3><p class="small">Every figure family, the MP4 and the simulation screenshots are downloadable individually above.</p><p class="small"><a href="MEDIA.md">Asset catalogue and provenance →</a></p></article></div></section></div>'''
index=index.replace('../validation/portfolio-capture-20260912T094720Z/executor.log','media/navigation-log.txt')
(OUT/"index.html").write_text(page("Research portfolio",index),encoding="utf-8")
(OUT/"assets/route-data.js").write_text("window.ROUTE_DATA = "+(OUT/"assets/routes.json").read_text(encoding="utf-8")+";\n",encoding="utf-8")
(OUT/"favicon.svg").write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#162b3b"/><path d="M14 43V21h15v22h21" fill="none" stroke="#67d0cd" stroke-width="6"/><circle cx="50" cy="43" r="6" fill="#efad6c"/></svg>',encoding="utf-8")
(OUT/"media/warehouse-navigation.vtt").write_text('WEBVTT\n\n00:00.000 --> 00:08.667\nSaved command: Go to the loading dock.\nTime-compressed Gazebo capture; Nav2 reports the goal reached.\n',encoding="utf-8")
print("Built portfolio index, route data, favicon and video captions.")

products=[
    ("waffle-pi","TurtleBot3 Waffle Pi · RPi4 4 GB",1681.40,"ROBOTIS","https://en.robotis.com/shop_en/item.php?it_id=901-0119-302","Complete-platform candidate. The listed SKU was out of stock; confirm the current sensor revision and shipping lead time."),
    ("jetson-orin","Jetson Orin Nano Super bundle",450.30,"Seeed Studio","https://www.seeedstudio.com/NVIDIAr-Jetson-Orintm-Nano-Super-Developer-Kit-Bundle.html","Optional compute upgrade for future perception or local-model work. This is the captured supplier bundle price, not an old launch MSRP."),
    ("rplidar","RPLIDAR A1M8-R6",99.00,"DFRobot","https://www.dfrobot.com/product-1125.html","Standalone sensor candidate for a custom chassis. Do not add it to a complete TurtleBot kit that already includes a scanner."),
    ("raspberry-pi","Raspberry Pi 5 · 8 GB",200.00,"Adafruit","https://www.adafruit.com/product/5813","Alternative computer for a future custom build. A Pi 5 is not a necessary extra purchase for the Pi-equipped TurtleBot kit."),
]
product_cards="".join(f'''<article class="media-card hardware-card"><a href="media/hardware/{slug}.png"><img loading="lazy" src="media/hardware/{slug}.png" alt="Dated {vendor} product-page screenshot for {name}"></a><div class="body"><span class="eyebrow">{vendor} / 12 Sep 2026</span><h3 style="margin-top:10px">{name}</h3><div class="price">${price:,.2f} <small>≈ AED {price*3.6725:,.2f}</small></div><p>{note}</p><a href="{url}">Check supplier listing ↗</a></div></article>''' for slug,name,price,vendor,url,note in products)
hardware=f'''<div class="wrap"><section class="subhero"><span class="eyebrow">Engineering proposal / not built or purchased</span><h1>From simulation<br>to a physical platform.</h1><p>A procurement study for a later robot build. Start with a platform close to the simulation and keep the model call in the cloud. Add GPU compute when a defined perception or local-inference experiment needs it.</p></section><div class="note"><strong>Price basis.</strong> Supplier pages checked on 12 September 2026. USD prices are displayed listings, not binding quotes. AED uses an explicit planning assumption of 3.6725 AED/USD. Shipping, import charges, tax, exchange fees, API usage and labour are excluded. Confirm current availability before purchase.</div><section class="section"><span class="eyebrow">01 / Candidate components</span><h2>Inspect the actual listings.</h2><div class="grid2">{product_cards}</div><p class="small">Screenshots belong to the named vendors and are included for attributed comparison. <a href="media/hardware/sources.json">Capture provenance →</a></p></section>
<section class="section"><span class="eyebrow">02 / Two routes to hardware</span><h2>Buy the required capability.</h2><div class="grid2"><article class="plate"><span class="tag">Lower-cost of these two options</span><h3 style="margin-top:20px">Navigation with the kit computer</h3><p class="small">Use the Waffle Pi kit's computer and keep the same cloud-planning architecture. Avoid buying a second computer and scanner at the start. This is a closer platform match, not a claim that it is the cheapest robot available.</p><p><strong>USD 1,781–1,931</strong><br><span class="small">≈ AED 6,542–7,093 before excluded costs</span></p><p class="small">Listed kit: $1,681.40. Add a clearly unquoted $100–250 engineering allowance for mounts, spare leads, storage needs and a suitable stop/power arrangement. Inventory the supplied kit before finalising the allowance.</p></article><article class="plate"><span class="tag">Optional research expansion</span><h3 style="margin-top:20px">Waffle platform with Orin compute</h3><p class="small">Add the Jetson Orin Nano Super bundle for a later GPU-based experiment. Mounting, regulated power and software bring-up require engineering; this combination has not been validated here.</p><p><strong>USD 2,382–2,742</strong><br><span class="small">≈ AED 8,747–10,069 before excluded costs</span></p><p class="small">Kit + observed Jetson bundle: $2,131.70. Common allowance: $100–250. Extra storage, power conversion and mounting allowance: $150–360. Allowances are estimates, not supplier quotes.</p></article></div><div class="note blue">The existing study uses <code>gpt-4o-mini</code> through an API. Installing a Jetson does not move that model onto the robot. A local model would be a new experimental condition requiring new measurements.</div></section>
<section class="section"><span class="eyebrow">03 / Bill of materials logic</span><h2>Account for the whole robot.</h2><div class="table-scroll"><table><thead><tr><th>Function</th><th>Kit-based plan</th><th>Engineering check before ordering</th></tr></thead><tbody>
<tr><td>Drive base and feedback</td><td>Kit chassis, wheels and DYNAMIXEL drive actuators</td><td>Check payload, wheel odometry calibration and mounting clearance; a kit is not a validated warehouse vehicle.</td></tr>
<tr><td>Motor interface</td><td>OpenCR controller supplied with the platform</td><td>Match firmware, USB/serial permissions, motor IDs and ROS interface.</td></tr>
<tr><td>Range sensing</td><td>Kit laser scanner; exact revision to confirm</td><td>ROBOTIS notes an October 2025 sensor change. Select the driver for the shipped unit. The $99 RPLIDAR is an alternative, not an assumed kit component.</td></tr>
<tr><td>Orientation and odometry</td><td>Platform IMU and wheel feedback</td><td>Characterise calibration, time stamps, frame alignment and noise before sensor fusion.</td></tr>
<tr><td>Main computer</td><td>Included Raspberry Pi; optional Orin upgrade</td><td>Choose OS/ROS versions together. Orin and the original Jetson Nano are different platforms.</td></tr>
<tr><td>Power</td><td>Confirm battery and charger in the exact kit inventory</td><td>For added compute, size a protected regulated rail for peak load. Verify connectors, polarity, fusing and accessible motor stop. Do not assume a developer kit plugs directly into the robot battery.</td></tr>
<tr><td>Storage, cabling and structure</td><td>Purchase only what the delivered kit lacks</td><td>Storage endurance, USB strain relief, cable routing, rigid sensor mounts and cooling clearance.</td></tr>
<tr><td>Optional camera</td><td>Defer for the present navigation-only scope</td><td>Add only with a defined perception question, supported driver and measured power/bandwidth budget.</td></tr>
</tbody></table></div><p class="small">Platform component reference: <a href="https://emanual.robotis.com/docs/en/platform/turtlebot3/features/">ROBOTIS TurtleBot3 documentation</a>. This is a procurement checklist, not a tested assembly or electrical wiring design.</p></section>
<section class="section"><span class="eyebrow">04 / Software compatibility</span><h2>Keep the versions deliberate.</h2><div class="grid2"><article class="plate"><h3>Preserve the dissertation environment</h3><p class="small">The recorded study uses ROS2 Humble, Ubuntu 22.04 and Gazebo Classic 11. Preserve those versions for replay. A simulator migration should be a separate change with fresh validation.</p><p class="small">For Orin, <a href="https://developer.nvidia.com/embedded/jetpack-sdk-621">JetPack 6.2.1</a> documents an Ubuntu 22.04 base and Orin support. It is a candidate compatibility path, not a verified installation on this robot.</p></article><article class="plate"><h3>Replace ground truth with measured localisation</h3><p class="small">A physical robot needs wheel/sensor feedback and a localisation strategy. Map creation with SLAM Toolbox, localisation on a saved map with AMCL, and optional IMU/odometry fusion are future integration choices. The dissertation's scripted map and static transform do not establish real-world localisation.</p><p class="small">Candidate source projects: <a href="https://github.com/SteveMacenski/slam_toolbox">SLAM Toolbox</a>, <a href="https://github.com/ros-navigation/navigation2">Nav2 / AMCL</a>, <a href="https://github.com/cra-ros-pkg/robot_localization">robot_localization</a>. Pin compatible versions and test them together.</p></article></div><figure class="plate" style="margin-top:24px"><img loading="lazy" src="assets/hardware-architecture.svg" alt="Proposed robot's compute, sensors, motor control and power interfaces"></figure></section>
<section class="section body-copy"><h2>Acceptance before autonomous trials</h2><ol><li>Verify physical stop, stable power, motor direction and correct sensor frames while stationary or supported.</li><li>Measure wheel odometry and localisation against known distances and poses.</li><li>Run single-goal navigation, then sequences, with recorded outcomes and clear stopping criteria.</li><li>Test primary success, primary failure with reachable fallback, and both destinations unavailable as separate conditions.</li><li>Only then introduce new language samples; keep translation correctness separate from navigation outcomes.</li></ol><p class="small">These are proposed validation stages. No physical-robot results are claimed in this repository.</p><a href="hardware-costs.csv" download>Download the quoted-component cost table (CSV) ↓</a></section></div>'''
(OUT/"hardware.html").write_text(page("Proposed hardware and costs",hardware),encoding="utf-8")
import csv
with (OUT/"hardware-costs.csv").open("w",newline="",encoding="utf-8") as file:
    writer=csv.writer(file); writer.writerow(["component","vendor","listed_usd","planning_aed","source_url","checked_date","scope"])
    for slug,name,price,vendor,url,note in products:
        writer.writerow([name,vendor,f"{price:.2f}",f"{price*3.6725:.2f}",url,"2026-09-12",note])

reproduce='''<div class="wrap"><section class="subhero"><span class="eyebrow">Reproduction / software / interfaces</span><h1>Inspect, run,<br>then extend.</h1><p>Start with saved plans and software tests. Use the dated evidence directories to distinguish the original experiment from the corrected executor.</p></section><section class="section" id="stack"><h2>The software that actually runs.</h2><div class="table-scroll"><table><thead><tr><th>Layer</th><th>Used in this project</th><th>Role / evidence</th></tr></thead><tbody>
<tr><td>Host</td><td>Windows 11 + WSL Ubuntu 22.04</td><td>ROS and simulation run inside WSL.</td></tr>
<tr><td>Language planning</td><td>Python · gpt-4o-mini · temperature 0</td><td>One API call, JSON-object mode, named locations. <a href="../../src/planner.py">Planner source</a>.</td></tr>
<tr><td>Data contract</td><td>JSON Schema · jsonschema</td><td>Historical evaluation schemas remain unchanged. A separate September runtime contract gates execution.</td></tr>
<tr><td>Middleware</td><td>ROS2 Humble · Cyclone DDS</td><td>Loopback configuration for this WSL host. A distributed physical deployment needs a different network configuration.</td></tr>
<tr><td>Simulation</td><td>Gazebo Classic 11 · TurtleBot3 Waffle</td><td>Scripted warehouse, simulated range sensor and ground-truth odometry.</td></tr>
<tr><td>Global planning</td><td>NavFn · <code>use_astar: false</code></td><td><code>nav2_navfn_planner/NavfnPlanner</code> in the saved configuration.</td></tr>
<tr><td>Path following</td><td>Regulated Pure Pursuit</td><td>Desired linear speed 0.26 m/s; 0.25 m / 0.25 rad goal tolerances.</td></tr>
<tr><td>Costmaps</td><td>Static, obstacle / voxel, inflation layers</td><td>Configured scan observations on <code>/scan</code>; inflated obstacles guide navigation clearance.</td></tr>
<tr><td>Recovery</td><td>Nav2 behaviour server and per-step executor policies</td><td>Configured spin/back-up/wait behaviours; explicit abort, skip, retry, perimeter and later fallback handling.</td></tr>
<tr><td>Localisation in the recorded simulation</td><td>Map server + static map→odom transform</td><td>Ground truth. SLAM Toolbox was not used to obtain these runs.</td></tr>
<tr><td>Figures and documents</td><td>Matplotlib · LaTeX/IEEEtran · BibTeX</td><td>Data-driven figures with PNG, SVG and PDF exports; eight-page report draft.</td></tr>
</tbody></table></div><p class="small">Source of implementation details: <a href="../../ros2_ws/src/nl_nav2_executor/params/nav2_params.yaml">Nav2 parameters</a>, <a href="../../ros2_ws/src/nl_nav2_executor/launch/warehouse_sim.launch.py">simulation launch</a>, <a href="../../setup/sim-env.sh">environment script</a>. Listed plugins are configured components; this is not a claim that every behaviour was triggered in the demos.</p></section>
<section class="section body-copy"><span class="eyebrow">01 / No API key required</span><h2>Run the software checks.</h2><pre><code># From the repository root, using an environment with pytest + jsonschema:
python -m pytest ros2_ws/src/nl_nav2_executor/test -q

# Deterministic replay of the saved v3 branch, with A unavailable:
python ros2_ws/src/nl_nav2_executor/scripts/dry_run.py \\
  --plan docs/validation/execution-check-20260911T172852Z/v3-L4-12-trial0.json \\
  --blocked storage_zone_a</code></pre><p>The expected successful visit is <code>storage_zone_b</code>. Without <code>--blocked</code>, only A is visited. Blocking both A and B produces exit code 1. These are mock navigation checks; no robot moves.</p><pre><code># WSL: rebuild and verify installed ROS imports and runtime resources
bash setup/verify-runtime-fixes.sh</code></pre></section>
<section class="section body-copy"><span class="eyebrow">02 / In WSL Ubuntu 22.04</span><h2>Run the actual warehouse.</h2><pre><code># ROS2 Humble, Gazebo Classic 11, Nav2 and TurtleBot3 packages must be installed.
source setup/sim-env.sh
cd ros2_ws
colcon build --packages-select nl_nav2_executor --symlink-install
source install/setup.bash
ros2 launch nl_nav2_executor warehouse_sim.launch.py</code></pre><p>In a second terminal, from the repository root:</p><pre><code>source setup/sim-env.sh
source ros2_ws/install/setup.bash
ros2 run nl_nav2_executor execute_plan \\
  --plan docs/validation/execution-check-20260911T172852Z/v2-L1-01-trial0.json \\
  --map map/warehouse_map.json</code></pre><p>Wait for both the map-server and navigation lifecycle managers to be active. The robot starts at the charging dock. Exit code 0 means completed execution; 1 means incomplete, aborted or deferred; 2 means rejected input. A fallback success is reported separately from reaching the primary destination.</p><div class="note">The current executor differs from the one used for the earlier 9/9 replays. See <a href="../validation/runtime-fixes-20260912/README.md">the correction record</a> and its preserved original files. Running old plans on new code is not an exact reproduction of old runtime behaviour.</div></section>
<section class="section body-copy"><span class="eyebrow">03 / Optional live model call</span><h2>Type a new command.</h2><pre><code># Configure an API key privately in the environment or local .env.
# The following command makes one billed API call.
export PROMPT_VERSION=v2
python src/run_pipeline.py "Go to the loading dock" \\
  --out /tmp/warehouse-plan.json</code></pre><p>The bridge validates the returned plan before writing an executable output. A clarification response does not trigger navigation. Select v3 explicitly for the fallback representation; the default planner prompt in the existing source remains v1 unless <code>PROMPT_VERSION</code> is set.</p></section>
<section class="section body-copy"><span class="eyebrow">04 / Visual artifacts</span><h2>Rebuild the presentation material.</h2><pre><code># In a Python environment with Matplotlib:
python setup/build-portfolio-figures.py
python setup/build-portfolio-pages.py

# Open docs/portfolio/index.html directly, or serve the repository locally:
python -m http.server 8765 --bind 127.0.0.1
# Then visit http://127.0.0.1:8765/docs/portfolio/

# Genuine new Gazebo captures (WSL; requires Xvfb, ImageMagick, xdotool):
bash setup/capture-portfolio.sh
bash setup/capture-portfolio.sh detail</code></pre><p>Capture scripts create dated directories and stop only the process groups they launch. Raw frame sequences and ROS logs stay out of the presentation pack. The report is rebuilt outside this repository while it is under assessment.</p><a href="MEDIA.md">Media export and attribution notes →</a></section></div>'''
(OUT/"reproduce.html").write_text(page("Reproduction and software",reproduce),encoding="utf-8")
print("Built hardware and reproduction pages with a dated component CSV.")
